"""add retry_index field to node-execution model

Revision ID: 0acba21814ad
Revises: b608381a3e95
Create Date: 2024-12-18 01:44:28.321657

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acba21814ad'
down_revision = 'b608381a3e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_node_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_index', sa.Integer(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_node_executions', schema=None) as batch_op:
        batch_op.drop_column('retry_index')

    # ### end Alembic commands ###
